# Generated by Django 4.1 on 2022-08-05 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('qtPomodoros', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Tareas',
                'verbose_name_plural': 'Tareas',
            },
        ),
        migrations.CreateModel(
            name='PomodoroTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('completed', models.BooleanField()),
                ('time', models.TimeField()),
                ('typeOf', models.IntegerField()),
                ('startTime', models.TimeField()),
                ('finishTime', models.TimeField()),
                ('idTask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pomodoros.task')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pomodoro',
                'verbose_name_plural': 'Pomodoros',
            },
        ),
    ]
